name: test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print list of dir
        run: |
          ls -al
          pwd
          mkdir -p /tmp/bak
          echo "test" > test.log
          ls -al /tmp/bak
          cat /tmp/bak/test.log
