name: test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print list of dir
        run: |
          ls -al
          pwd

      - name: test for docker
        run: |
          mkdir -p /tmp/bak
          docker save -o /tmp/bak/ubuntu.tar ubuntu:18.04
          ls -al /tmp/bak
